version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run: npm test
  test2:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run: npm test
workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build:
        filters:
          branches:
            only:
              - /develop/
      - test:
          requires:
            - build
