version: 2.1
orbs:
  node: circleci/node:12.16.1
jobs:
  build-and-test:
    steps:
      - checkout
      - run: npm install
      - run: npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test
