version: 2.1
jobs:
  build:
    branches:
      only:
        - develop
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run: npm test
workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
